# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  gamereservewebapi:
    image: gamereservewebapi
    build:
      context: .
      dockerfile: src/GameReserve.WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5110:5110
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
