// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reservations.Infrastructure.Data;

#nullable disable

namespace Reservations.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ReservationsContext))]
    [Migration("20260924101329_AddInterceptor")]
    partial class AddInterceptor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reservations.Domain.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservationProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReservationProfileId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Reservations.Domain.Aggregates.ReservationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ReservationProfiles");
                });

            modelBuilder.Entity("SharedKernel.Domain.Primivites.DomainEvent.DomainEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservationProfileId");

                    b.ToTable("DomainEvent");
                });

            modelBuilder.Entity("Reservations.Domain.Aggregates.Reservation", b =>
                {
                    b.HasOne("Reservations.Domain.Aggregates.ReservationProfile", null)
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SharedKernel.Domain.Primivites.DomainEvent.DomainEvent", b =>
                {
                    b.HasOne("Reservations.Domain.Aggregates.ReservationProfile", null)
                        .WithMany("DomainEvents")
                        .HasForeignKey("ReservationProfileId");
                });

            modelBuilder.Entity("Reservations.Domain.Aggregates.ReservationProfile", b =>
                {
                    b.Navigation("DomainEvents");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
